#!/bin/sh
# Using external pipe with st, give a dmenu prompt of output lines allowing the
# user to copy one line.
# xclip required for this script.
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
chosen="$(cat "$tmpfile" | grep -E '^.{6,}$' | grep -v "$ps1" | grep -v "@" | sed '/^$/d' | sort | uniq | dmenu -p "Copy line:" -i -l 4 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
grep "$chosen" "$tmpfile" | xclip -selection clipboard
